### ISSUE TITLE
Some dependencies are missing in the pip installation instructions

### ISSUE THREAD

**Issue by marlonsmathias** [hippalectryon-0/pyloggrid#3]
The install instructions via pip are missing the dependencies for OpenMP.

To test installation, I opened a fresh container and followed the instructions in the documentation, installing the library via pip.

This led to the following error:

```
# python3 NS3D.py 
Traceback (most recent call last):
  File "/home/log-grid/Simulations/NS3D.py", line 15, in <module>
    from pyloggrid.LogGrid.Framework import Grid, Solver
  File "/home/log-grid/Simulations/../pyloggrid/LogGrid/Framework.py", line 27, in <module>
    from pyloggrid.Libs.IOLib import load_step, read_json_settings, save_step, update_json_settings
  File "/home/log-grid/Simulations/../pyloggrid/Libs/IOLib.py", line 23, in <module>
    from pyloggrid.LogGrid.Grid import Grid
  File "/home/log-grid/Simulations/../pyloggrid/LogGrid/Grid.py", line 28, in <module>
    import pyloggrid.LogGrid.compute_convolution_kernel as conv_kernel_generator
ImportError: libomp.so.5: cannot open shared object file: No such file or directory
```

This was fixed by installing the libomp-dev library, which is not mentioned in the documentation.

**Comment by hippalectryon-0** [comment]
You're correct, thanks for the info. libomp-dev is installed when via the manual `install.sh`, but we indeed forgot to add the requirements for the pip version. I'll update the documentation shortly.
