### ISSUE TITLE
Missing images in the documentation

### ISSUE THREAD

**Issue by marlonsmathias** [hippalectryon-0/pyloggrid#4]
Most (if not all) images of the documentation are missing. This makes it harder to understand the examples and we can't see the benchmarks.

**Comment by hippalectryon-0** [comment]
Can you confirm that you're using the `joss` branch of the documentation ? On my end images appear fine.

![image](https://github.com/hippalectryon-0/pyloggrid/assets/6502864/dd0d12c3-c04f-4195-8dd2-7e0e6c924cb4)

**Comment by marlonsmathias** [comment]
Thanks for the response! I was using the latest branch. The images work fine in the joss branch.
