### ISSUE TITLE
Permission for git clone

### ISSUE THREAD

**Issue by marlonsmathias** [hippalectryon-0/pyloggrid#5]
The provided command for install via git results in permission denied:

```
#git clone git@github.com:hippalectryon-0/pyloggrid.git
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

However, I was able to clone it with
 `
git clone https://github.com/hippalectryon-0/pyloggrid.git
`

**Comment by hippalectryon-0** [comment]
Same as #4 , switch to the `joss` documentation branch, where the docs use the new url `git clone https://github.com/hippalectryon-0/pyloggrid.git`
