### ISSUE TITLE
Suggestion: More examples in the documentation

### ISSUE THREAD

**Issue by marlonsmathias** [hippalectryon-0/pyloggrid#6]
The documentation would be greatly improved if more examples were available, giving more detail on, for instance, the boundary conditions.

My suggestion is to use a well-known problem, such as the Couette flow or the Rayleigh-Benard problem.

**Comment by hippalectryon-0** [comment]
Sorry for the long delay.

I believe you made this comment before I updated the documentation. Does https://pyloggrid.readthedocs.io/en/joss/tutorial/tutorial_first_simu.html#what-we-re-simulating bring some light to your question ?

As we're fully in Fourier space, the BC are 3D-perodic.
